name: configure the login banner
  hosts: routers
  connection: network_cli
  gather_facts: no

  ios_banner:
    banner: login
    text: |
      this is Indra login banner
      that contains a multiline
      string
    state: present
